MD029: false # MD029/ol-prefix: Ordered list item prefix
MD013: false # MD013/line-length: Line length
MD024: false # MD024/no-duplicate-heading/no-duplicate-header: Multiple headings with the same content
MD036: false # MD036/no-emphasis-as-heading/no-emphasis-as-header: Emphasis used instead of a heading
